### ISSUE TITLE
Great work, Does it download the model checkpoints as well?

### ISSUE THREAD

**Issue by amrrs** [kadirnar/segment-anything-video#10]
I've not tried it yet, just wanted to check if it also downloads the model checkpoints.

**Comment by kadirnar** [comment]
I updated the codes. Just write model_type. I also added video support.
```
from metaseg import SegAutoMaskGenerator

# If gpu memory is not enough, reduce the points_per_side and points_per_batch.

SegAutoMaskGenerator(
        model_type="vit_h", # "vit_l", "vit_b"
        source= "test.png", # test.mp4
        device="cuda", # "cpu" or "cuda"
        show=True, 
        points_per_side=16, # Optional
        points_per_batch=64, # Optional
)
```
download_model(): https://github.com/kadirnar/segment-anything-pip/blob/main/metaseg/utils/file.py

**Comment by amrrs** [comment]
Thank you @kadirnar - This link doesn't exist - https://github.com/kadirnar/segment-anything-pip/blob/main/metaseg/utils/file.py

**Comment by amrrs** [comment]
@kadirnar your library is covered here - https://www.youtube.com/watch?v=8SvQqZCd-ww

**Comment by kadirnar** [comment]
I updated the codes.
https://github.com/kadirnar/segment-anything-video/blob/main/metaseg/utils/file_utils.py

Thank you for the youtube video. I will add it to the readme tomorrow.
