### ISSUE TITLE
ImportError with SegAutoMaskGenerator from metaseg package

### ISSUE THREAD

**Issue by RazaProdigy** [kadirnar/segment-anything-video#23]
### Description:

I'm getting an ImportError when trying to import SegAutoMaskGenerator from the metaseg package. Here's the error message:

`ImportError: cannot import name 'SamAutomaticMaskGenerator' from partially initialized module 'metaseg' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/metaseg/__init__.py)`

Screenshot:
![image](https://user-images.githubusercontent.com/61845660/230783007-4aba906b-e9d9-4617-b7f4-aa037b5bb80e.png)

### Steps to reproduce:

1. Install the metaseg package (pip install metaseg) on Google Colab.
2. Run the following code:
`from metaseg import SegAutoMaskGenerator`

### Expected behavior:

The SegAutoMaskGenerator class should be successfully imported without any errors.

### Actual behavior:

The ImportError is raised when trying to import SegAutoMaskGenerator.

### Environment:

Python version: 3.9.16
Runtime: Google colab (with standard gpu)

**Comment by kadirnar** [comment]
Did you look at the readme file?
```
from metaseg import SegAutoMaskPredictor, SegManualMaskPredictor

# If gpu memory is not enough, reduce the points_per_side and points_per_batch.

# For image

autoseg_image = SegAutoMaskPredictor().save_image(
    source="image.jpg",
    model_type="vit_l", # vit_l, vit_h, vit_b
    points_per_side=16, 
    points_per_batch=64,
    min_area=0,
)

# For video

autoseg_video = SegAutoMaskPredictor().save_video(
    source="video.mp4",
    model_type="vit_l", # vit_l, vit_h, vit_b
    points_per_side=16, 
    points_per_batch=64,
    min_area=1000,
)

# For manuel box selection

seg_manual_mask_generator = SegManualMaskPredictor().save_image(
    source="image.jpg",
    model_type="vit_l", # vit_l, vit_h, vit_b
    x0=100,
    y0=100,
    x1=200,
    y1=200,
)
```

**Comment by RazaProdigy** [comment]
This seems to solve the issue!
`from metaseg import SegAutoMaskPredictor, SegManualMaskPredictor`

Thank you!
