### ISSUE TITLE
ONNX support / Segmentation output

### ISSUE THREAD

**Issue by Ashoka74** [kadirnar/segment-anything-video#37]
Thank you for this great wrapper! 

I was wondering if there was support for ONNX models for faster inference. 
Also; is it possible to export each layer individually as in the SAM demo? 

Finally; I tried the cam streaming (setting source=0) but no success so far!

**Comment by kadirnar** [comment]
I will add the onnx format later. I am currently working on draw and SAHI library integration. Do you want to add Onxx support?
