### ISSUE TITLE
SegAutoMaskPredictor().save_image returning error

### ISSUE THREAD

**Issue by voidxd** [kadirnar/segment-anything-video#42]
Hello,

It seems something has changed in the code and .save_image isn't working anymore.

I have tried the following but there is no output image generated.

```
autoseg_image = SegAutoMaskPredictor().image_predict(
    source="smudge.png",
    model_type="vit_l",
    points_per_side=16, 
    points_per_batch=64,
    min_area=0,
    output_path='output.jpg'
)
```

I have also tried setting `save=True` and I'm getting the following error:
![image](https://user-images.githubusercontent.com/58847957/231278658-49d0749a-99c7-4c4d-857e-1bc6b0ed1c2e.png)

Could you help, please?

**Comment by kadirnar** [comment]
I updated the function names.
```
from metaseg import SegAutoMaskPredictor, SegManualMaskPredictor

results = SegAutoMaskPredictor().image_predict(
    source="image.jpg",
    model_type="vit_l", # vit_l, vit_h, vit_b
    points_per_side=16, 
    points_per_batch=64,
    min_area=0,
    output_path="output.jpg",
    show=True,
    save=False,
)
```
