### ISSUE TITLE
Dose this repo support tracking in video?

### ISSUE THREAD

**Issue by KainingYing** [kadirnar/segment-anything-video#46]

**Comment by kadirnar** [comment]
@bhack , @KainingYing 

Which tracking algorithm do you want?  Have you looked at the Torchyolo library? I added the tracker library for Yolo models. 

https://github.com/kadirnar/torchyolo

My Tracker Repos:

https://github.com/kadirnar/Norfair-Track
https://github.com/kadirnar/ocsort-pip
https://github.com/kadirnar/bytetrack-pip
https://github.com/kadirnar/strongsort-pip
https://github.com/kadirnar/sort-pip

**Comment by kadirnar** [comment]
I added the [SAHI](https://github.com/obss/sahi) algorithm for small object detection.

https://github.com/kadirnar/segment-anything-video#sahi--segment-anything

**Comment by bhack** [comment]
These tracking algorithm are good but I don't think that these are mask tracking.

See the the upstream ticket datasets related leaderboards.

**Comment by KainingYing** [comment]
thanks

**Comment by kadirnar** [comment]
> @kadirnar With you algos you can reproduce something like: https://github.com/yahooo-mds/OSTrack_SAM
> 
> But it will not have the quality and temporal consistency as using the embedding with VOS specific networks like the ones performing in the mentioned datasets.

https://github.com/kadirnar/segment-anything-video/issues/6#issuecomment-1505328823

**Comment by kadirnar** [comment]
https://github.com/gaomingqi/Track-Anything

**Comment by egeozguroglu** [comment]
Dear @kadirnar, you've linked the Track Anything repository in your comment above, which interestingly has the exact metaseg demo in their repo (demo.py). To clarify: (1) Does metaseg support tracking of segmentation masks through videos? (2) Is there a link between metaseg and Track Anything?

**Comment by kadirnar** [comment]
The Metaseg library does not have a tracker feature. You can view the feature list here:
https://github.com/kadirnar/segment-anything-video#extra-features

The Track-Anything repo used to use the metaseg library but no longer does.
