### ISSUE TITLE
Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Sequential-circuits** [kadirnar/segment-anything-video#62]
(base) root@185:~/Track-Anything# python app.py --device cuda:0 --sam_model_type vit_h --port 80
/root/anaconda3/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Initializing BaseSegmenter to cuda:0

**Comment by kadirnar** [comment]
I don't know the cause of the error. You shouldn't ask the Track-Anything repo.

**Comment by onuralpszr** [comment]
This is more like an issue between pytorch/torchvision and cuda, it seems like you install via anaconda and something in that installation could be missing or it could be your nvidia driver issue as well.  Also you looks like using Track-Anything so it would be also best to as them as well. 

Thank you.
