### ISSUE TITLE
how to get more objects like segment anything online demo?

### ISSUE THREAD

**Issue by zouxiaodong** [kadirnar/segment-anything-video#98]
the image has a high resolution : 5472x3648 
**How can we achieve a similar detection performance as the online demo for detecting numerous small targets, while using SAM+YOLOV8 that currently detects only a few targets**

![pests](https://github.com/kadirnar/segment-anything-video/assets/46236818/6a29dfd8-a8c8-4fbe-9de9-5744c750e248)
--------------------------------------------------
https://segment-anything.com/demo result : got lot of objects
![image](https://github.com/kadirnar/segment-anything-video/assets/46236818/d9cfcd35-3290-4bb5-9a63-8557115b3cce)

-----------sam+yolov8-seg
![image](https://github.com/kadirnar/segment-anything-video/assets/46236818/9d198697-cd0b-4571-8356-40952ff8aa24)

from metaseg import SahiAutoSegmentation, sahi_sliced_predict

image_path = "pests.jpg"
boxes = sahi_sliced_predict(
    image_path=image_path,
    detection_model_type="yolov8",  # yolov8, detectron2, mmdetection, torchvision
    detection_model_path="yolov8x-seg.pt",
    conf_th=0.25,
    image_size=1024,
    slice_height=256,
    slice_width=256,
    overlap_height_ratio=0.2,
    overlap_width_ratio=0.2,
)

SahiAutoSegmentation().image_predict(
    source=image_path,
    model_type="vit_b",
    input_box=boxes,
    multimask_output=False,
    random_color=False,
    show=True,
    save=False,
)

**Comment by kadirnar** [comment]
Does SAHI algorithm support yolov8 segmentation model? I think no. This repo uses Sam's detection results and performs segmentation.

**Comment by zouxiaodong** [comment]
sorry,I made a mistake, yolov8 only outputs boxes.In my usage scenario, boxes only need to pass the size of the image.
tks
